server:
  port: 8080

eureka:
  instance:
    hostname: localhost

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: http://localhost:8082/
          predicates:
            - Path=/authentication-service/**
          filters:
            - RewritePath=/authentication-service(?<segment>/?.*), $\{segment}
        - id: config-server
          uri: http://localhost:8888/
          predicates:
            - Path=/config-server/**
          filters:
            - RewritePath=/config-server(?<segment>/?.*), $\{segment}
        - id: chat-service
          uri: http://localhost:8084/
          predicates:
            - Path=/chat-service/**
          filters:
            - RewritePath=/chat-service(?<segment>/?.*), $\{segment}
        - id: eureka-server
          uri: http://localhost:8761/
          predicates:
            - Path=/eureka-server/**
          filters:
            - RewritePath=/eureka-server(?<segment>/?.*), $\{segment}
        - id: notification-service
          uri: http://localhost:8086/
          predicates:
            - Path=/notification-service/**
          filters:
            - RewritePath=/notification-service(?<segment>/?.*), $\{segment}
        - id: slot-handling-service
          uri: http://localhost:8090/
          predicates:
            - Path=/slot-handling/**
          filters:
            - RewritePath=/slot-handling(?<segment>/?.*), $\{segment}
        - id: ticker-handling-service
          uri: http://localhost:8092/
          predicates:
            - Path=/ticker-handling-service/**
          filters:
            - RewritePath=/ticket-handling-service(?<segment>/?.*), $\{segment}
        - id: user-service
          uri: http://localhost:8094/
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service(?<segment>/?.*), $\{segment}
